// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nursing_Service.Persistence.Contexts;

#nullable disable

namespace Nursing_Service.Persistence.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Nursing_Service.Domain.Entities.Nurse.NurseCanDoService", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("NurseId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NurseId");

                    b.HasIndex("ServiceId");

                    b.ToTable("NurseCanDoService");
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.Patient.Patient", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IllnessHistory")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.Patient.PatientNeedService", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPast")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("NurseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NurseRepost")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ServiceDateTime")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SuperVisorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NurseId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SuperVisorId");

                    b.ToTable("PatientNeedService");
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.RequestForm.RequestForm", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RequestForms");
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.Service.Service", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("MinDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.User.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email", "DeletedDateTime")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.Nurse.Nurse", b =>
                {
                    b.HasBaseType("Nursing_Service.Domain.Entities.User.User");

                    b.Property<string>("NurseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartWorkingInCompany")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("SuperVisorId")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("WorkHistoryInYear")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SuperVisorId");

                    b.ToTable("Nurses", (string)null);
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.SuperVisor.SuperVisor", b =>
                {
                    b.HasBaseType("Nursing_Service.Domain.Entities.User.User");

                    b.Property<int>("Shift")
                        .HasColumnType("INTEGER");

                    b.ToTable("Supervisors", (string)null);
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.Nurse.NurseCanDoService", b =>
                {
                    b.HasOne("Nursing_Service.Domain.Entities.Nurse.Nurse", "Nurse")
                        .WithMany("DoService")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nursing_Service.Domain.Entities.Service.Service", "Service")
                        .WithMany("NurseDoService")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.Patient.PatientNeedService", b =>
                {
                    b.HasOne("Nursing_Service.Domain.Entities.Nurse.Nurse", "AssignNurse")
                        .WithMany("ServicesForPatients")
                        .HasForeignKey("NurseId");

                    b.HasOne("Nursing_Service.Domain.Entities.Patient.Patient", "Patient")
                        .WithMany("NeedServices")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nursing_Service.Domain.Entities.Service.Service", "Service")
                        .WithMany("PatientNeedServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nursing_Service.Domain.Entities.SuperVisor.SuperVisor", "AssignSuperVisor")
                        .WithMany()
                        .HasForeignKey("SuperVisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignNurse");

                    b.Navigation("AssignSuperVisor");

                    b.Navigation("Patient");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.Nurse.Nurse", b =>
                {
                    b.HasOne("Nursing_Service.Domain.Entities.User.User", null)
                        .WithOne()
                        .HasForeignKey("Nursing_Service.Domain.Entities.Nurse.Nurse", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nursing_Service.Domain.Entities.SuperVisor.SuperVisor", "SuperVisor")
                        .WithMany("SupervisorNurses")
                        .HasForeignKey("SuperVisorId");

                    b.Navigation("SuperVisor");
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.SuperVisor.SuperVisor", b =>
                {
                    b.HasOne("Nursing_Service.Domain.Entities.User.User", null)
                        .WithOne()
                        .HasForeignKey("Nursing_Service.Domain.Entities.SuperVisor.SuperVisor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.Patient.Patient", b =>
                {
                    b.Navigation("NeedServices");
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.Service.Service", b =>
                {
                    b.Navigation("NurseDoService");

                    b.Navigation("PatientNeedServices");
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.Nurse.Nurse", b =>
                {
                    b.Navigation("DoService");

                    b.Navigation("ServicesForPatients");
                });

            modelBuilder.Entity("Nursing_Service.Domain.Entities.SuperVisor.SuperVisor", b =>
                {
                    b.Navigation("SupervisorNurses");
                });
#pragma warning restore 612, 618
        }
    }
}
